import axios from 'axios'
import { isUpdated } from 'contentful-management'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Update, Create, getAllEntries} from '../pages/api/hello'

const requesttest = async() => {
 const result = await Update()
 console.log(result)
}

const getVotes = async () => {
  const result = await getAllEntries()
  console.log(result)
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
<button onClick={() => requesttest()}>TEST</button>
<button onClick={() => getVotes()}>getAllEntries</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
